FIX: Running Python things while being in this directory may fail as there was a 'copy.py' file (expect a 'AttributeError: module 'copy' has no attribute 'deepcopy'